"""recipes table

Revision ID: ce255796a9b5
Revises: 71f6a3b4378d
Create Date: 2026-04-26 22:11:43.274420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce255796a9b5'
down_revision = '71f6a3b4378d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('long_desc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('short_desc', sa.String(length=512), nullable=False))
        batch_op.add_column(sa.Column('categories', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ingredients', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('instructions', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_recipes_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_title'))
        batch_op.drop_column('updated')
        batch_op.drop_column('instructions')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('tags')
        batch_op.drop_column('categories')
        batch_op.drop_column('short_desc')
        batch_op.drop_column('long_desc')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
